// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadStatus():Promise<number>;

export function DownloadVPN():Promise<string>;

export function RequiresUpdate():Promise<boolean>;

export function StartVPN():Promise<boolean>;

export function StopVPN():Promise<boolean>;

export function WriteConfig(arg1:string):Promise<boolean>;
