// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckConfig():Promise<boolean>;

export function DownloadStatus():Promise<number>;

export function DownloadVPN():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function RequiresUpdate():Promise<boolean>;
