// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckConfig() {
  return window['go']['main']['App']['CheckConfig']();
}

export function DownloadVPN() {
  return window['go']['main']['App']['DownloadVPN']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RequiresUpdate() {
  return window['go']['main']['App']['RequiresUpdate']();
}
