// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadStatus() {
  return window['go']['main']['App']['DownloadStatus']();
}

export function DownloadVPN() {
  return window['go']['main']['App']['DownloadVPN']();
}

export function RequiresUpdate() {
  return window['go']['main']['App']['RequiresUpdate']();
}

export function StartVPN() {
  return window['go']['main']['App']['StartVPN']();
}

export function StopVPN() {
  return window['go']['main']['App']['StopVPN']();
}

export function WriteConfig(arg1) {
  return window['go']['main']['App']['WriteConfig'](arg1);
}
